### ISSUE TITLE
Aliases cannot start with Dotclear's URL handlers [+ add a redirect option?]

### ISSUE THREAD

**Issue by p4bl0-** [JcDenis/alias#1]
Hey,

I wanted to have a `/pages/foobar` alias for a `/post/yyyy/mm/foo-bar-baz` url, but it seems that this plugin cannot create aliases that starts with existing URL handlers (like `post/`, `pages/`, `tag/`, etc.).

This should probably either be fixed or explicited in the README :).

-----

If it is fixed so that aliases are checked for before dispatching the URL to other handlers, it would be nice to also have the option to make aliases that *redirect* to their target URL.

With this feature, we could use this plugin for example to change the URL of a post and redirect the old one to the new one :).
(I would really appreciate to be able to do that, and never found a plugin to do so properly!)

Cheers!

**Comment by JcDenis** [comment]
I tried my best to do that. But this changes how the plugin works, it stops using dotclear URL handlers and bypass them by catching a behavior...
Not sure there are no bugs.
