### ISSUE TITLE
Exception php 7.4

### ISSUE THREAD

**Issue by gibus** [JcDenis/alias#2]
Salut,

En php 7.4, il y a une exception qui fait que les pages d'admin sont en erreur HTTP 500:

`Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/alternc/g/gibuskro/dotclear/plugins/alias/src/Backend.php on line 74`

Visiblement la syntaxe `function (bool|FlatBackupItem $line, FlatImportV2 $bk)` n'est pas supporté en php 7, je n'ai aucune idée de ce à quoi elle sert, mais enlever `bool|` et de même ligne 84, résout le problème.

**Comment by gibus** [comment]
OK, il s'agit d'union type cf. https://php.watch/versions/8.0/union-types et donc oui, ce n'est pas supporté avant php 8. Je sais qu'il est prévu que le core dotclear exigera PHP 8.1 à la fin de l'année, mais d'ici là, il ne faudrait pas que les plugins cassent la compatibilité php 7. Suivant les hébergements, ce n'est pas toujours évident de passe à php 8…

**Comment by JcDenis** [comment]
Effectivement, à force de mélanger les versions, je suis allé un peu vite ici. Je corrige pour le laisser en php7.4 encore un peu.

**Comment by gibus** [comment]
Super, merci!
